# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
FLOAT_CFLAGS_EXTRA := -c -m32 -fno-builtin -I$(LIB_COMMON_DIR)

$(FLOAT_OBJ): $(LIB_COMMON_DIR)/FLOAT.c $(LIB_COMMON_DIR)/FLOAT.h
	$(call make_command, $(CC), $(FLOAT_CFLAGS_EXTRA), cc $<, $<)
